export interface IEnvironment {
    DATABASE_URL,
    FIREBASE_API_KEY,
    FIREBASE_APP_ID,
    FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID,
    FIREBASE_SENDER_ID,
    FIREBASE_STORAGE_BUCKET,
    NODE_ENV,
    TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN,
    TWILIO_CHAT_API_SECRET,
    TWILIO_CHAT_AUTOPILOT_URL,
    TWILIO_CHAT_SERVICE_SID
}